/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacao;

import Controle.Conexao;
import Modelagem.Aluno;
import Modelagem.Session;
import Modelagem.VerificadorFases;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fatec-dsm2
 */
public class FEstatistica extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Aluno a = new Aluno();
    private Aluno alunoLogado;
    private int idAluno;
    
    Color preto = new Color(0,0,0,64);
    Color vermelhoPastel = new Color(239,91,106);
    Color azulPastel = new Color(108,210,255);
    
    public FEstatistica() {
        initComponents();
        conexao = Conexao.conecta();
        alunoLogado = Session.getInstance().getAlunoLogado();
        if (alunoLogado == null) {
            // Se não houver aluno logado, redirecione para a tela de login
            new FLogin().setVisible(true);
            this.dispose();
            return;
        }
        
        panel_check1.setVisible(false);
        panel_check2.setVisible(false);
        panel_check3.setVisible(false);
        
        idAluno = alunoLogado.getIdAluno();
        double pontos = alunoLogado.getPontosTotais();
        int nivel = (int)(pontos/100);
        double progressoNivel = pontos % 100;
        String foto = alunoLogado.getFoto();
        barra_xp.setValue((int) progressoNivel);
        int fasesConcluidas = alunoLogado.getFasesConcluidas();
        lbl_fases_concluidas.setText(Integer.toString(fasesConcluidas));
        
         String verConquistas = "select c.nomeConquista, c.descCOnquista from alunosXconquistas axc \n" +
        "join conquistas c on c.idConquista = axc.idConquista \n" +
        "join alunos a on a.idAluno = axc.idAluno \n" +
        "where a.idAluno = ?;";
        
       // Lista para armazenar todas as conquistas
        ArrayList<ArrayList<String>> conquistasTotais = new ArrayList<>();

        try {
            pst = conexao.prepareStatement(verConquistas);
            pst.setInt(1, idAluno);
            rs = pst.executeQuery();

            // Iterar sobre o ResultSet para recuperar todos os resultados
            while (rs.next()) {
                String nomeConquista = rs.getString(1);
                String descConquista = rs.getString(2);

                // Lista para armazenar um par (nomeAluno, nomeConquista)
                ArrayList<String> conquista = new ArrayList<>();
                conquista.add(nomeConquista);
                conquista.add(descConquista);

                // Adicionar a lista de conquista na lista de conquistas totais
                conquistasTotais.add(conquista);
            }

            // Exemplo de uso das conquistas totais para exibir nos JLabels
            JPanel[] checkPanels = {panel_check1, panel_check2, panel_check3};

            for (int i = 0; i < conquistasTotais.size() && i < checkPanels.length; i++) {
                checkPanels[i].setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        VerificadorFases vfases = new VerificadorFases(conexao);
        String[] estadosFases = vfases.verificarFases(1, idAluno); // Verifica as fases da região 1
            
        System.out.println("Fase Visual: " + estadosFases[0]);
        System.out.println("Fase Números: " + estadosFases[1]);
        System.out.println("Fase Ouvir: " + estadosFases[2]);
        System.out.println("Fase Observacao: " + estadosFases[3]);
        
        //conquista1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customScrollPane1 = new Visualizacao.CustomScrollPane();
        panelGradiente = new Visualizacao.PanelGradiente();
        panelPretoOpac2 = new Visualizacao.PanelPretoOpac();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound1 = new Visualizacao.PanelRound();
        barra_xp = new Visualizacao.ProgressBar();
        panelRound2 = new Visualizacao.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_fases_concluidas = new javax.swing.JLabel();
        panelRound3 = new Visualizacao.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        panelRound4 = new Visualizacao.PanelRound();
        jLabel14 = new javax.swing.JLabel();
        customSeparator1 = new Visualizacao.CustomSeparator();
        customSeparator2 = new Visualizacao.CustomSeparator();
        panel_conquistas = new Visualizacao.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        conquista4 = new Visualizacao.PanelRound();
        lbl_nome2 = new javax.swing.JLabel();
        lbl_desc2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel_check2 = new Visualizacao.PanelRound();
        iconCheck2 = new javax.swing.JLabel();
        conquista6 = new Visualizacao.PanelRound();
        lbl_nome1 = new javax.swing.JLabel();
        lbl_desc1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel_check1 = new Visualizacao.PanelRound();
        iconCheck = new javax.swing.JLabel();
        conquista7 = new Visualizacao.PanelRound();
        lbl_nome3 = new javax.swing.JLabel();
        lbl_desc3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panel_check3 = new Visualizacao.PanelRound();
        iconCheck3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customScrollPane1.setBorder(null);

        panelGradiente.setPreferredSize(new java.awt.Dimension(475, 834));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estatísticas");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-voltar-branco.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);

        barra_xp.setBorder(null);
        barra_xp.setValue(300);
        barra_xp.setColorString(new java.awt.Color(255, 255, 255));
        barra_xp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barra_xp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(barra_xp, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setRoundTopLeft(40);
        panelRound2.setRoundTopRight(40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-fases.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Atividades");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Completas");

        lbl_fases_concluidas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_fases_concluidas.setForeground(new java.awt.Color(102, 102, 102));
        lbl_fases_concluidas.setText("8");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_fases_concluidas))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lbl_fases_concluidas))
                .addGap(13, 13, 13))
        );

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nível do mundo");

        panelRound4.setBackground(new java.awt.Color(128, 210, 91));
        panelRound4.setRoundBottomLeft(30);
        panelRound4.setRoundBottomRight(30);
        panelRound4.setRoundTopLeft(30);
        panelRound4.setRoundTopRight(30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("1");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        customSeparator1.setColor(new java.awt.Color(128, 210, 91));
        customSeparator1.setDashed(true);
        customSeparator1.setThickness(5);

        customSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        customSeparator2.setColor(new java.awt.Color(128, 210, 91));
        customSeparator2.setDashed(true);
        customSeparator2.setThickness(5);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(customSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound3Layout.createSequentialGroup()
                            .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                            .addComponent(customSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addComponent(customSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        panel_conquistas.setBackground(new java.awt.Color(255, 255, 255));
        panel_conquistas.setPreferredSize(new java.awt.Dimension(388, 333));
        panel_conquistas.setRoundBottomLeft(40);
        panel_conquistas.setRoundBottomRight(40);
        panel_conquistas.setRoundTopLeft(40);
        panel_conquistas.setRoundTopRight(40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Conquistas");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        conquista4.setBackground(new java.awt.Color(239, 91, 106));
        conquista4.setRoundBottomLeft(40);
        conquista4.setRoundBottomRight(40);
        conquista4.setRoundTopLeft(40);
        conquista4.setRoundTopRight(40);

        lbl_nome2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nome2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome2.setText("A todo o vapor!");

        lbl_desc2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_desc2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_desc2.setText("Terminou quatro fases");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-medalha2.png"))); // NOI18N

        panel_check2.setBackground(new java.awt.Color(255, 255, 255));
        panel_check2.setPreferredSize(new java.awt.Dimension(45, 45));
        panel_check2.setRoundBottomLeft(100);
        panel_check2.setRoundBottomRight(100);
        panel_check2.setRoundTopLeft(100);
        panel_check2.setRoundTopRight(100);

        iconCheck2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-check-conquista.png"))); // NOI18N

        javax.swing.GroupLayout panel_check2Layout = new javax.swing.GroupLayout(panel_check2);
        panel_check2.setLayout(panel_check2Layout);
        panel_check2Layout.setHorizontalGroup(
            panel_check2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_check2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(iconCheck2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panel_check2Layout.setVerticalGroup(
            panel_check2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_check2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconCheck2)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout conquista4Layout = new javax.swing.GroupLayout(conquista4);
        conquista4.setLayout(conquista4Layout);
        conquista4Layout.setHorizontalGroup(
            conquista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conquista4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(conquista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_desc2)
                    .addComponent(lbl_nome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_check2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        conquista4Layout.setVerticalGroup(
            conquista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conquista4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(conquista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(conquista4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(conquista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_check2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(conquista4Layout.createSequentialGroup()
                                .addComponent(lbl_nome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_desc2)))))
                .addGap(11, 11, 11))
        );

        conquista6.setBackground(new java.awt.Color(128, 210, 91));
        conquista6.setRoundBottomLeft(40);
        conquista6.setRoundBottomRight(40);
        conquista6.setRoundTopLeft(40);
        conquista6.setRoundTopRight(40);

        lbl_nome1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nome1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome1.setText("Iniciando!");

        lbl_desc1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_desc1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_desc1.setText("Terminou uma fase");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-medalha2.png"))); // NOI18N

        panel_check1.setBackground(new java.awt.Color(255, 255, 255));
        panel_check1.setPreferredSize(new java.awt.Dimension(45, 45));
        panel_check1.setRoundBottomLeft(100);
        panel_check1.setRoundBottomRight(100);
        panel_check1.setRoundTopLeft(100);
        panel_check1.setRoundTopRight(100);

        iconCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-check-conquista.png"))); // NOI18N

        javax.swing.GroupLayout panel_check1Layout = new javax.swing.GroupLayout(panel_check1);
        panel_check1.setLayout(panel_check1Layout);
        panel_check1Layout.setHorizontalGroup(
            panel_check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_check1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(iconCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panel_check1Layout.setVerticalGroup(
            panel_check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_check1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconCheck)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout conquista6Layout = new javax.swing.GroupLayout(conquista6);
        conquista6.setLayout(conquista6Layout);
        conquista6Layout.setHorizontalGroup(
            conquista6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conquista6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(conquista6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nome1)
                    .addComponent(lbl_desc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(panel_check1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        conquista6Layout.setVerticalGroup(
            conquista6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conquista6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(conquista6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(conquista6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(conquista6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_check1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(conquista6Layout.createSequentialGroup()
                                .addComponent(lbl_nome1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_desc1)))))
                .addGap(11, 11, 11))
        );

        conquista7.setBackground(new java.awt.Color(83, 194, 242));
        conquista7.setRoundBottomLeft(40);
        conquista7.setRoundBottomRight(40);
        conquista7.setRoundTopLeft(40);
        conquista7.setRoundTopRight(40);

        lbl_nome3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_nome3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome3.setText("Mundo concluído!");

        lbl_desc3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_desc3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_desc3.setText("Terminou um mundo");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-medalha2.png"))); // NOI18N

        panel_check3.setBackground(new java.awt.Color(255, 255, 255));
        panel_check3.setPreferredSize(new java.awt.Dimension(45, 45));
        panel_check3.setRoundBottomLeft(100);
        panel_check3.setRoundBottomRight(100);
        panel_check3.setRoundTopLeft(100);
        panel_check3.setRoundTopRight(100);

        iconCheck3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-check-conquista.png"))); // NOI18N

        javax.swing.GroupLayout panel_check3Layout = new javax.swing.GroupLayout(panel_check3);
        panel_check3.setLayout(panel_check3Layout);
        panel_check3Layout.setHorizontalGroup(
            panel_check3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_check3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(iconCheck3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panel_check3Layout.setVerticalGroup(
            panel_check3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_check3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(iconCheck3)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout conquista7Layout = new javax.swing.GroupLayout(conquista7);
        conquista7.setLayout(conquista7Layout);
        conquista7Layout.setHorizontalGroup(
            conquista7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conquista7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addGroup(conquista7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nome3)
                    .addComponent(lbl_desc3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_check3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        conquista7Layout.setVerticalGroup(
            conquista7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conquista7Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(conquista7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(conquista7Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(conquista7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_check3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(conquista7Layout.createSequentialGroup()
                                .addComponent(lbl_nome3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_desc3)))))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout panel_conquistasLayout = new javax.swing.GroupLayout(panel_conquistas);
        panel_conquistas.setLayout(panel_conquistasLayout);
        panel_conquistasLayout.setHorizontalGroup(
            panel_conquistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_conquistasLayout.createSequentialGroup()
                .addGroup(panel_conquistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_conquistasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_conquistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(conquista6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(conquista7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(conquista4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_conquistasLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel7)))
                .addGap(25, 25, 25))
        );
        panel_conquistasLayout.setVerticalGroup(
            panel_conquistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_conquistasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(conquista6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(conquista4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(conquista7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout panelPretoOpac2Layout = new javax.swing.GroupLayout(panelPretoOpac2);
        panelPretoOpac2.setLayout(panelPretoOpac2Layout);
        panelPretoOpac2Layout.setHorizontalGroup(
            panelPretoOpac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretoOpac2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelPretoOpac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPretoOpac2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(125, 125, 125))
                    .addGroup(panelPretoOpac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addGroup(panelPretoOpac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPretoOpac2Layout.createSequentialGroup()
                                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panel_conquistas, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        panelPretoOpac2Layout.setVerticalGroup(
            panelPretoOpac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretoOpac2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPretoOpac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel_conquistas, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGradienteLayout = new javax.swing.GroupLayout(panelGradiente);
        panelGradiente.setLayout(panelGradienteLayout);
        panelGradienteLayout.setHorizontalGroup(
            panelGradienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPretoOpac2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGradienteLayout.setVerticalGroup(
            panelGradienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPretoOpac2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        customScrollPane1.setViewportView(panelGradiente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new FPerfil().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEstatistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEstatistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEstatistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEstatistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEstatistica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Visualizacao.ProgressBar barra_xp;
    private Visualizacao.PanelRound conquista4;
    private Visualizacao.PanelRound conquista6;
    private Visualizacao.PanelRound conquista7;
    private Visualizacao.CustomScrollPane customScrollPane1;
    private Visualizacao.CustomSeparator customSeparator1;
    private Visualizacao.CustomSeparator customSeparator2;
    private javax.swing.JLabel iconCheck;
    private javax.swing.JLabel iconCheck2;
    private javax.swing.JLabel iconCheck3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_desc1;
    private javax.swing.JLabel lbl_desc2;
    private javax.swing.JLabel lbl_desc3;
    private javax.swing.JLabel lbl_fases_concluidas;
    private javax.swing.JLabel lbl_nome1;
    private javax.swing.JLabel lbl_nome2;
    private javax.swing.JLabel lbl_nome3;
    private Visualizacao.PanelGradiente panelGradiente;
    private Visualizacao.PanelPretoOpac panelPretoOpac2;
    private Visualizacao.PanelRound panelRound1;
    private Visualizacao.PanelRound panelRound2;
    private Visualizacao.PanelRound panelRound3;
    private Visualizacao.PanelRound panelRound4;
    private Visualizacao.PanelRound panel_check1;
    private Visualizacao.PanelRound panel_check2;
    private Visualizacao.PanelRound panel_check3;
    private Visualizacao.PanelRound panel_conquistas;
    // End of variables declaration//GEN-END:variables
}
