/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacao;

import Controle.Conexao;
import Modelagem.Aluno;
import Modelagem.Session;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author João
 */
public class FMundos extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    Color vermelhoPastel = new Color(239,91,106);
    Color azulPastel = new Color(108,210,255);
    Color azul = new Color(83, 194, 242);
    Color verde = new Color(128,210,91);
    Color vermelho = new Color(239,91,106);
    
    private Aluno alunoLogado;
    private int idAluno;
    private boolean naturalClicado = false;
    private boolean geloClicado = false;
    private boolean fogoClicado = false;
    int mundo = 1;
    
    public FMundos() {
        initComponents();
        conexao = Conexao.conecta();
        alunoLogado = Session.getInstance().getAlunoLogado();
        if (alunoLogado == null) {
            // Se não houver aluno logado, redirecione para a tela de login
            new FLogin().setVisible(true);
            this.dispose();
            return;
        }
        idAluno = alunoLogado.getIdAluno();
        double pontos = alunoLogado.getPontosTotais();
        String ranque = alunoLogado.getRanque();
        
        lbl_pontos.setText(Double.toString(pontos));
        lbl_ranque.setText(ranque);
        
        String verConquistas = "select count(*) from alunosXconquistas where idAluno = ?";
        try {
            pst = conexao.prepareStatement(verConquistas);
            pst.setInt(1, idAluno);
            rs = pst.executeQuery();

            if (rs.next()) {
                int qtdMedalhas = rs.getInt(1);
                lbl_medalhas.setText(Integer.toString(qtdMedalhas));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        panelSlide.init(new PanelMundos("Mundo - 1", "Mundo Natural", new ImageIcon("src/Imagens/mundo-natureza2.png")), new PanelMundos("Mundo - 2", "Mundo Congelado", new ImageIcon("src/Imagens/mundo-congelado.png")), new PanelMundos("Mundo - 3", "Mundo Flamejante", new ImageIcon("src/Imagens/mundo-flamejante3.png")));
        panelSlide.setAnimate(5);
        this.setLayout(new BorderLayout());
        this.add(panelScrollMundos, BorderLayout.CENTER);
        this.add(menu, BorderLayout.SOUTH);
        panel_natural_grande.setVisible(false);
        linha_verde.setVisible(false);
        panel_gelo_grande.setVisible(false);
        linha_azul.setVisible(false);
        panel_fogo_grande.setVisible(false);
        linha_vermelha.setVisible(false);
        btn_mundo1.setColor(verde);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelScrollMundos = new Visualizacao.CustomScrollPane();
        panelGradiente = new Visualizacao.PanelGradiente();
        panelRound1 = new Visualizacao.PanelRound();
        panelSlide = new Visualizacao.PanelSlide();
        panelRound2 = new Visualizacao.PanelRound();
        btn_mundo3 = new Visualizacao.BotaoCustomizado();
        btn_mundo2 = new Visualizacao.BotaoCustomizado();
        btn_mundo1 = new Visualizacao.BotaoCustomizado();
        panelSombra3 = new Visualizacao.PanelSombra();
        jLabel1 = new javax.swing.JLabel();
        panelRound3 = new Visualizacao.PanelRound();
        panelGradiente1 = new Visualizacao.PanelGradiente();
        panelRound4 = new Visualizacao.PanelRound();
        panel_natural_grande = new Visualizacao.PanelRound();
        panelRoundBorda1 = new Visualizacao.PanelRoundBorda();
        panelRound11 = new Visualizacao.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        linha_vermelha = new Visualizacao.PanelRound();
        panel_gelo = new Visualizacao.PanelRound();
        panelRoundBorda2 = new Visualizacao.PanelRoundBorda();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel_fogo = new Visualizacao.PanelRound();
        panelRoundBorda5 = new Visualizacao.PanelRoundBorda();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelRound10 = new Visualizacao.PanelRound();
        panelRound12 = new Visualizacao.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel_natural = new Visualizacao.PanelRound();
        panelRoundBorda4 = new Visualizacao.PanelRoundBorda();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panel_gelo_grande = new Visualizacao.PanelRound();
        panelRoundBorda6 = new Visualizacao.PanelRoundBorda();
        panelRound13 = new Visualizacao.PanelRound();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel_fogo_grande = new Visualizacao.PanelRound();
        panelRoundBorda7 = new Visualizacao.PanelRoundBorda();
        panelRound14 = new Visualizacao.PanelRound();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        linha_azul = new Visualizacao.PanelRound();
        linha_verde = new Visualizacao.PanelRound();
        panelSombra5 = new Visualizacao.PanelSombra();
        lbl_medalhas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelSombra6 = new Visualizacao.PanelSombra();
        lbl_ranque = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        panelSombra7 = new Visualizacao.PanelSombra();
        lbl_pontos = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        menu.setBackground(new java.awt.Color(76, 76, 76));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone perfil.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone home.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone menu hamburguer.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelScrollMundos.setBorder(null);

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        panelSlide.setPreferredSize(new java.awt.Dimension(418, 409));

        javax.swing.GroupLayout panelSlideLayout = new javax.swing.GroupLayout(panelSlide);
        panelSlide.setLayout(panelSlideLayout);
        panelSlideLayout.setHorizontalGroup(
            panelSlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelSlideLayout.setVerticalGroup(
            panelSlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        panelRound2.setBackground(new java.awt.Color(76, 76, 76));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);

        btn_mundo3.setBorderColor(new java.awt.Color(102, 102, 102));
        btn_mundo3.setColorClick(new java.awt.Color(255, 255, 255));
        btn_mundo3.setColorOver(new java.awt.Color(204, 204, 204));
        btn_mundo3.setPreferredSize(new java.awt.Dimension(30, 40));
        btn_mundo3.setRadius(100);
        btn_mundo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mundo3ActionPerformed(evt);
            }
        });

        btn_mundo2.setBorderColor(new java.awt.Color(102, 102, 102));
        btn_mundo2.setColorClick(new java.awt.Color(255, 255, 255));
        btn_mundo2.setColorOver(new java.awt.Color(204, 204, 204));
        btn_mundo2.setPreferredSize(new java.awt.Dimension(30, 40));
        btn_mundo2.setRadius(100);
        btn_mundo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mundo2ActionPerformed(evt);
            }
        });

        btn_mundo1.setBorderColor(new java.awt.Color(102, 102, 102));
        btn_mundo1.setColorClick(new java.awt.Color(255, 255, 255));
        btn_mundo1.setColorOver(new java.awt.Color(204, 204, 204));
        btn_mundo1.setPreferredSize(new java.awt.Dimension(30, 40));
        btn_mundo1.setRadius(100);
        btn_mundo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mundo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_mundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btn_mundo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btn_mundo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mundo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mundo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSombra3.setBackground(new java.awt.Color(76, 76, 76));
        panelSombra3.setPreferredSize(new java.awt.Dimension(195, 60));
        panelSombra3.setShadowOpacity(0.2F);
        panelSombra3.setShadowSize(3);
        panelSombra3.setShadowType(Visualizacao.ShadowType.BOT_LEFT);
        panelSombra3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSombra3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Entrar");

        javax.swing.GroupLayout panelSombra3Layout = new javax.swing.GroupLayout(panelSombra3);
        panelSombra3.setLayout(panelSombra3Layout);
        panelSombra3Layout.setHorizontalGroup(
            panelSombra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSombra3Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panelSombra3Layout.setVerticalGroup(
            panelSombra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSombra3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(239, 91, 106));
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelGradiente1.setGradientDirection(Visualizacao.PanelGradiente.GradientDirection.VERTICAL);

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);

        panel_natural_grande.setBackground(new java.awt.Color(76, 76, 76));
        panel_natural_grande.setImg(new ImageIcon("src/Imagens/img-natureza-fundo.png"));
        panel_natural_grande.setRoundBottomLeft(30);
        panel_natural_grande.setRoundBottomRight(30);
        panel_natural_grande.setRoundTopLeft(30);
        panel_natural_grande.setRoundTopRight(30);
        panel_natural_grande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_natural_grandeMouseClicked(evt);
            }
        });

        panelRoundBorda1.setBackground(new java.awt.Color(255, 255, 255));
        panelRoundBorda1.setBorderWidth(5);
        panelRoundBorda1.setGradientEndColor(new java.awt.Color(128, 210, 91));
        panelRoundBorda1.setGradientStartColor(new java.awt.Color(128, 210, 91));
        panelRoundBorda1.setRadius(100);

        javax.swing.GroupLayout panelRoundBorda1Layout = new javax.swing.GroupLayout(panelRoundBorda1);
        panelRoundBorda1.setLayout(panelRoundBorda1Layout);
        panelRoundBorda1Layout.setHorizontalGroup(
            panelRoundBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelRoundBorda1Layout.setVerticalGroup(
            panelRoundBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelRound11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound11.setRoundBottomLeft(100);
        panelRound11.setRoundBottomRight(100);
        panelRound11.setRoundTopLeft(100);
        panelRound11.setRoundTopRight(100);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-seta-direita.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(15, 18));

        javax.swing.GroupLayout panelRound11Layout = new javax.swing.GroupLayout(panelRound11);
        panelRound11.setLayout(panelRound11Layout);
        panelRound11Layout.setHorizontalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panelRound11Layout.setVerticalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound11Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nature Realm");

        javax.swing.GroupLayout panel_natural_grandeLayout = new javax.swing.GroupLayout(panel_natural_grande);
        panel_natural_grande.setLayout(panel_natural_grandeLayout);
        panel_natural_grandeLayout.setHorizontalGroup(
            panel_natural_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_natural_grandeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelRoundBorda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panel_natural_grandeLayout.setVerticalGroup(
            panel_natural_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_natural_grandeLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(panel_natural_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(panelRoundBorda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        linha_vermelha.setBackground(new java.awt.Color(255, 98, 98));
        linha_vermelha.setRoundBottomLeft(30);
        linha_vermelha.setRoundBottomRight(30);

        javax.swing.GroupLayout linha_vermelhaLayout = new javax.swing.GroupLayout(linha_vermelha);
        linha_vermelha.setLayout(linha_vermelhaLayout);
        linha_vermelhaLayout.setHorizontalGroup(
            linha_vermelhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        linha_vermelhaLayout.setVerticalGroup(
            linha_vermelhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel_gelo.setBackground(new java.awt.Color(76, 76, 76));
        panel_gelo.setRoundBottomLeft(30);
        panel_gelo.setRoundBottomRight(30);
        panel_gelo.setRoundTopLeft(30);
        panel_gelo.setRoundTopRight(30);
        panel_gelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_geloMouseClicked(evt);
            }
        });

        panelRoundBorda2.setBackground(new java.awt.Color(255, 255, 255));
        panelRoundBorda2.setBorderWidth(5);
        panelRoundBorda2.setGradientEndColor(new java.awt.Color(121, 188, 204));
        panelRoundBorda2.setGradientStartColor(new java.awt.Color(121, 188, 204));
        panelRoundBorda2.setRadius(100);

        javax.swing.GroupLayout panelRoundBorda2Layout = new javax.swing.GroupLayout(panelRoundBorda2);
        panelRoundBorda2.setLayout(panelRoundBorda2Layout);
        panelRoundBorda2Layout.setHorizontalGroup(
            panelRoundBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelRoundBorda2Layout.setVerticalGroup(
            panelRoundBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ice Kingdom");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-seta-baixo.png"))); // NOI18N

        javax.swing.GroupLayout panel_geloLayout = new javax.swing.GroupLayout(panel_gelo);
        panel_gelo.setLayout(panel_geloLayout);
        panel_geloLayout.setHorizontalGroup(
            panel_geloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_geloLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelRoundBorda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(jLabel11)
                .addGap(24, 24, 24))
        );
        panel_geloLayout.setVerticalGroup(
            panel_geloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_geloLayout.createSequentialGroup()
                .addGroup(panel_geloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_geloLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panel_geloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRoundBorda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addGroup(panel_geloLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)))
                .addGap(11, 11, 11))
        );

        panel_fogo.setBackground(new java.awt.Color(76, 76, 76));
        panel_fogo.setRoundBottomLeft(30);
        panel_fogo.setRoundBottomRight(30);
        panel_fogo.setRoundTopLeft(30);
        panel_fogo.setRoundTopRight(30);
        panel_fogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_fogoMouseClicked(evt);
            }
        });

        panelRoundBorda5.setBackground(new java.awt.Color(255, 255, 255));
        panelRoundBorda5.setBorderWidth(5);
        panelRoundBorda5.setGradientEndColor(new java.awt.Color(255, 98, 98));
        panelRoundBorda5.setGradientStartColor(new java.awt.Color(255, 98, 98));
        panelRoundBorda5.setRadius(100);

        javax.swing.GroupLayout panelRoundBorda5Layout = new javax.swing.GroupLayout(panelRoundBorda5);
        panelRoundBorda5.setLayout(panelRoundBorda5Layout);
        panelRoundBorda5Layout.setHorizontalGroup(
            panelRoundBorda5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelRoundBorda5Layout.setVerticalGroup(
            panelRoundBorda5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Volcano Islands");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-seta-baixo.png"))); // NOI18N

        javax.swing.GroupLayout panel_fogoLayout = new javax.swing.GroupLayout(panel_fogo);
        panel_fogo.setLayout(panel_fogoLayout);
        panel_fogoLayout.setHorizontalGroup(
            panel_fogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fogoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelRoundBorda5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(jLabel15)
                .addGap(26, 26, 26))
        );
        panel_fogoLayout.setVerticalGroup(
            panel_fogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fogoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_fogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelRoundBorda5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_fogoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)))
                .addGap(11, 11, 11))
        );

        panelRound10.setBackground(new java.awt.Color(76, 76, 76));
        panelRound10.setRoundBottomLeft(30);
        panelRound10.setRoundBottomRight(30);
        panelRound10.setRoundTopLeft(30);
        panelRound10.setRoundTopRight(30);
        panelRound10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound10MouseClicked(evt);
            }
        });

        panelRound12.setBackground(new java.awt.Color(255, 255, 255));
        panelRound12.setRoundBottomLeft(100);
        panelRound12.setRoundBottomRight(100);
        panelRound12.setRoundTopLeft(100);
        panelRound12.setRoundTopRight(100);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-seta-baixo.png"))); // NOI18N

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound12Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addGap(10, 10, 10))
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addGap(11, 11, 11))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mais mundos");

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(68, 68, 68)
                .addComponent(panelRound12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound10Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        panel_natural.setBackground(new java.awt.Color(76, 76, 76));
        panel_natural.setRoundBottomLeft(30);
        panel_natural.setRoundBottomRight(30);
        panel_natural.setRoundTopLeft(30);
        panel_natural.setRoundTopRight(30);
        panel_natural.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_naturalMouseClicked(evt);
            }
        });

        panelRoundBorda4.setBackground(new java.awt.Color(255, 255, 255));
        panelRoundBorda4.setBorderWidth(5);
        panelRoundBorda4.setGradientEndColor(new java.awt.Color(128, 210, 91));
        panelRoundBorda4.setGradientStartColor(new java.awt.Color(128, 210, 91));
        panelRoundBorda4.setRadius(100);

        javax.swing.GroupLayout panelRoundBorda4Layout = new javax.swing.GroupLayout(panelRoundBorda4);
        panelRoundBorda4.setLayout(panelRoundBorda4Layout);
        panelRoundBorda4Layout.setHorizontalGroup(
            panelRoundBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelRoundBorda4Layout.setVerticalGroup(
            panelRoundBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nature Realm");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-seta-baixo.png"))); // NOI18N

        javax.swing.GroupLayout panel_naturalLayout = new javax.swing.GroupLayout(panel_natural);
        panel_natural.setLayout(panel_naturalLayout);
        panel_naturalLayout.setHorizontalGroup(
            panel_naturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_naturalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelRoundBorda4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(jLabel21)
                .addGap(24, 24, 24))
        );
        panel_naturalLayout.setVerticalGroup(
            panel_naturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_naturalLayout.createSequentialGroup()
                .addGroup(panel_naturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_naturalLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panel_naturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRoundBorda4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addGroup(panel_naturalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel21)))
                .addGap(11, 11, 11))
        );

        panel_gelo_grande.setBackground(new java.awt.Color(76, 76, 76));
        panel_gelo_grande.setImg(new ImageIcon("src/Imagens/img-natureza-fundo.png"));
        panel_gelo_grande.setRoundBottomLeft(30);
        panel_gelo_grande.setRoundBottomRight(30);
        panel_gelo_grande.setRoundTopLeft(30);
        panel_gelo_grande.setRoundTopRight(30);
        panel_gelo_grande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_gelo_grandeMouseClicked(evt);
            }
        });

        panelRoundBorda6.setBackground(new java.awt.Color(255, 255, 255));
        panelRoundBorda6.setBorderWidth(5);
        panelRoundBorda6.setGradientEndColor(new java.awt.Color(121, 188, 204));
        panelRoundBorda6.setGradientStartColor(new java.awt.Color(121, 188, 204));
        panelRoundBorda6.setRadius(100);

        javax.swing.GroupLayout panelRoundBorda6Layout = new javax.swing.GroupLayout(panelRoundBorda6);
        panelRoundBorda6.setLayout(panelRoundBorda6Layout);
        panelRoundBorda6Layout.setHorizontalGroup(
            panelRoundBorda6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelRoundBorda6Layout.setVerticalGroup(
            panelRoundBorda6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setRoundBottomLeft(100);
        panelRound13.setRoundBottomRight(100);
        panelRound13.setRoundTopLeft(100);
        panelRound13.setRoundTopRight(100);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-seta-direita.png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(15, 18));

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ice Kingdom");

        javax.swing.GroupLayout panel_gelo_grandeLayout = new javax.swing.GroupLayout(panel_gelo_grande);
        panel_gelo_grande.setLayout(panel_gelo_grandeLayout);
        panel_gelo_grandeLayout.setHorizontalGroup(
            panel_gelo_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gelo_grandeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelRoundBorda6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panel_gelo_grandeLayout.setVerticalGroup(
            panel_gelo_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_gelo_grandeLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(panel_gelo_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(panelRoundBorda6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        panel_fogo_grande.setBackground(new java.awt.Color(76, 76, 76));
        panel_fogo_grande.setImg(new ImageIcon("src/Imagens/img-natureza-fundo.png"));
        panel_fogo_grande.setRoundBottomLeft(30);
        panel_fogo_grande.setRoundBottomRight(30);
        panel_fogo_grande.setRoundTopLeft(30);
        panel_fogo_grande.setRoundTopRight(30);
        panel_fogo_grande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_fogo_grandeMouseClicked(evt);
            }
        });

        panelRoundBorda7.setBackground(new java.awt.Color(255, 255, 255));
        panelRoundBorda7.setBorderWidth(5);
        panelRoundBorda7.setGradientEndColor(new java.awt.Color(255, 98, 98));
        panelRoundBorda7.setGradientStartColor(new java.awt.Color(255, 98, 98));
        panelRoundBorda7.setRadius(100);

        javax.swing.GroupLayout panelRoundBorda7Layout = new javax.swing.GroupLayout(panelRoundBorda7);
        panelRoundBorda7.setLayout(panelRoundBorda7Layout);
        panelRoundBorda7Layout.setHorizontalGroup(
            panelRoundBorda7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelRoundBorda7Layout.setVerticalGroup(
            panelRoundBorda7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelRound14.setBackground(new java.awt.Color(255, 255, 255));
        panelRound14.setRoundBottomLeft(100);
        panelRound14.setRoundBottomRight(100);
        panelRound14.setRoundTopLeft(100);
        panelRound14.setRoundTopRight(100);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-seta-direita.png"))); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(15, 18));

        javax.swing.GroupLayout panelRound14Layout = new javax.swing.GroupLayout(panelRound14);
        panelRound14.setLayout(panelRound14Layout);
        panelRound14Layout.setHorizontalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound14Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panelRound14Layout.setVerticalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound14Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ice Kingdom");

        javax.swing.GroupLayout panel_fogo_grandeLayout = new javax.swing.GroupLayout(panel_fogo_grande);
        panel_fogo_grande.setLayout(panel_fogo_grandeLayout);
        panel_fogo_grandeLayout.setHorizontalGroup(
            panel_fogo_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fogo_grandeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelRoundBorda7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panel_fogo_grandeLayout.setVerticalGroup(
            panel_fogo_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fogo_grandeLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(panel_fogo_grandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(panelRoundBorda7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        linha_azul.setBackground(new java.awt.Color(121, 188, 204));
        linha_azul.setRoundBottomLeft(30);
        linha_azul.setRoundBottomRight(30);

        javax.swing.GroupLayout linha_azulLayout = new javax.swing.GroupLayout(linha_azul);
        linha_azul.setLayout(linha_azulLayout);
        linha_azulLayout.setHorizontalGroup(
            linha_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        linha_azulLayout.setVerticalGroup(
            linha_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        linha_verde.setBackground(new java.awt.Color(128, 210, 91));
        linha_verde.setRoundBottomLeft(30);
        linha_verde.setRoundBottomRight(30);

        javax.swing.GroupLayout linha_verdeLayout = new javax.swing.GroupLayout(linha_verde);
        linha_verde.setLayout(linha_verdeLayout);
        linha_verdeLayout.setHorizontalGroup(
            linha_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        linha_verdeLayout.setVerticalGroup(
            linha_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel_gelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRound4Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(panel_gelo_grande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panel_fogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRound4Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panel_fogo_grande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelRound4Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(linha_vermelha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(panelRound10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRound4Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(linha_azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound4Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(panel_natural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRound4Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(panel_natural_grande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRound4Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(linha_verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panel_natural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_natural_grande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linha_verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_gelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_gelo_grande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linha_azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_fogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_fogo_grande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linha_vermelha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(panelRound10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGradiente1Layout = new javax.swing.GroupLayout(panelGradiente1);
        panelGradiente1.setLayout(panelGradiente1Layout);
        panelGradiente1Layout.setHorizontalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelGradiente1Layout.setVerticalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelGradiente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(panelSombra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panelSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSombra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelSombra5.setBackground(new java.awt.Color(255, 255, 255));
        panelSombra5.setPreferredSize(new java.awt.Dimension(131, 47));
        panelSombra5.setShadowOpacity(0.3F);

        lbl_medalhas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_medalhas.setForeground(new java.awt.Color(72, 72, 72));
        lbl_medalhas.setText("10");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-moeda.png"))); // NOI18N

        javax.swing.GroupLayout panelSombra5Layout = new javax.swing.GroupLayout(panelSombra5);
        panelSombra5.setLayout(panelSombra5Layout);
        panelSombra5Layout.setHorizontalGroup(
            panelSombra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSombra5Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(lbl_medalhas)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelSombra5Layout.setVerticalGroup(
            panelSombra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSombra5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_medalhas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSombra5Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelSombra6.setBackground(new java.awt.Color(255, 255, 255));
        panelSombra6.setPreferredSize(new java.awt.Dimension(131, 47));
        panelSombra6.setShadowOpacity(0.3F);

        lbl_ranque.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ranque.setForeground(new java.awt.Color(72, 72, 72));
        lbl_ranque.setText("1");
        lbl_ranque.setToolTipText("");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-estrela.png"))); // NOI18N

        javax.swing.GroupLayout panelSombra6Layout = new javax.swing.GroupLayout(panelSombra6);
        panelSombra6.setLayout(panelSombra6Layout);
        panelSombra6Layout.setHorizontalGroup(
            panelSombra6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSombra6Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_ranque)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelSombra6Layout.setVerticalGroup(
            panelSombra6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSombra6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_ranque)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSombra7.setBackground(new java.awt.Color(255, 255, 255));
        panelSombra7.setPreferredSize(new java.awt.Dimension(131, 54));
        panelSombra7.setShadowOpacity(0.3F);

        lbl_pontos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_pontos.setForeground(new java.awt.Color(72, 72, 72));
        lbl_pontos.setText("100");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-fogo.png"))); // NOI18N

        javax.swing.GroupLayout panelSombra7Layout = new javax.swing.GroupLayout(panelSombra7);
        panelSombra7.setLayout(panelSombra7Layout);
        panelSombra7Layout.setHorizontalGroup(
            panelSombra7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSombra7Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_pontos)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelSombra7Layout.setVerticalGroup(
            panelSombra7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSombra7Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(panelSombra7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_pontos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGradienteLayout = new javax.swing.GroupLayout(panelGradiente);
        panelGradiente.setLayout(panelGradienteLayout);
        panelGradienteLayout.setHorizontalGroup(
            panelGradienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradienteLayout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelGradienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelSombra7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(panelSombra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(panelSombra6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGradienteLayout.setVerticalGroup(
            panelGradienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradienteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelGradienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSombra5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(panelSombra6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(panelSombra7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelScrollMundos.setViewportView(panelGradiente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScrollMundos, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScrollMundos, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mundo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mundo3ActionPerformed
        panelSlide.show(2);
        mundo = 3;
        if(mundo == 3){
            btn_mundo3.setColor(vermelho);
            btn_mundo1.setColor(new Color(255, 255, 255));
            btn_mundo2.setColor(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_btn_mundo3ActionPerformed

    private void btn_mundo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mundo2ActionPerformed
        panelSlide.show(1);
        mundo = 2;
        if(mundo == 2){
            btn_mundo2.setColor(azul);
            btn_mundo1.setColor(new Color(255, 255, 255));
            btn_mundo3.setColor(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_btn_mundo2ActionPerformed

    private void btn_mundo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mundo1ActionPerformed
        panelSlide.show(0);
        mundo = 1;
        if(mundo == 1){
            btn_mundo1.setColor(verde);
            btn_mundo2.setColor(new Color(255, 255, 255));
            btn_mundo3.setColor(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_btn_mundo1ActionPerformed

    private void panelSombra3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSombra3MouseClicked
        if(mundo == 1){
            new FRegiao().setVisible(true);
            dispose();
        } else{
            ImageIcon icon = new ImageIcon("src/Imagens/icon-mundos-alerta.png");
            AlertaGeral alert = new AlertaGeral(FMundos.this, icon, "Mundos", "Mundo em desenvolvimento...", 25, 25);
            alert.setVisible(true);
        }
    }//GEN-LAST:event_panelSombra3MouseClicked

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6jLabel1MouseClicked
        new FPerfil(this).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6jLabel1MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        new FOpcoes(this).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void panel_naturalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_naturalMouseClicked
        if (!naturalClicado) {
            // Define o ícone de clique se ainda não foi clicado
            panel_natural_grande.setVisible(true);
            linha_verde.setVisible(true);
            naturalClicado = true;
        } else {
            panel_natural_grande.setVisible(false);
            linha_verde.setVisible(false);
            naturalClicado = false;
        }
    }//GEN-LAST:event_panel_naturalMouseClicked

    private void panel_geloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_geloMouseClicked
        if (!geloClicado) {
            // Define o ícone de clique se ainda não foi clicado
            panel_gelo_grande.setVisible(true);
            linha_azul.setVisible(true);
            geloClicado = true;
        } else {
            panel_gelo_grande.setVisible(false);
            linha_azul.setVisible(false);
            geloClicado = false;
        }
    }//GEN-LAST:event_panel_geloMouseClicked

    private void panel_fogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fogoMouseClicked
        if (!fogoClicado) {
            // Define o ícone de clique se ainda não foi clicado
            panel_fogo_grande.setVisible(true);
            linha_vermelha.setVisible(true);
            fogoClicado = true;
        } else {
            panel_fogo_grande.setVisible(false);
            linha_vermelha.setVisible(false);
            fogoClicado = false;
        }
    }//GEN-LAST:event_panel_fogoMouseClicked

    private void panel_natural_grandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_natural_grandeMouseClicked
        new FRegiao().setVisible(true);
        dispose();
    }//GEN-LAST:event_panel_natural_grandeMouseClicked

    private void panel_gelo_grandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_gelo_grandeMouseClicked
        ImageIcon icon = new ImageIcon("src/Imagens/icon-mundos-alerta.png");
        AlertaGeral alert = new AlertaGeral(FMundos.this, icon, "Mundos", "Mundo em desenvolvimento...", 25, 25);
        alert.setVisible(true);
    }//GEN-LAST:event_panel_gelo_grandeMouseClicked

    private void panel_fogo_grandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_fogo_grandeMouseClicked
        ImageIcon icon = new ImageIcon("src/Imagens/icon-mundos-alerta.png");
        AlertaGeral alert = new AlertaGeral(FMundos.this, icon, "Mundos", "Mundo em desenvolvimento...", 25, 25);
        alert.setVisible(true);
    }//GEN-LAST:event_panel_fogo_grandeMouseClicked

    private void panelRound10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound10MouseClicked
        ImageIcon icon = new ImageIcon("src/Imagens/icon-mundos-alerta.png");
        AlertaGeral alert = new AlertaGeral(FMundos.this, icon, "Mundos", "Mundo em desenvolvimento...", 25, 25);
        alert.setVisible(true);
    }//GEN-LAST:event_panelRound10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMundos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMundos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMundos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMundos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMundos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Visualizacao.BotaoCustomizado btn_mundo1;
    private Visualizacao.BotaoCustomizado btn_mundo2;
    private Visualizacao.BotaoCustomizado btn_mundo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_medalhas;
    private javax.swing.JLabel lbl_pontos;
    private javax.swing.JLabel lbl_ranque;
    private Visualizacao.PanelRound linha_azul;
    private Visualizacao.PanelRound linha_verde;
    private Visualizacao.PanelRound linha_vermelha;
    private javax.swing.JPanel menu;
    private Visualizacao.PanelGradiente panelGradiente;
    private Visualizacao.PanelGradiente panelGradiente1;
    private Visualizacao.PanelRound panelRound1;
    private Visualizacao.PanelRound panelRound10;
    private Visualizacao.PanelRound panelRound11;
    private Visualizacao.PanelRound panelRound12;
    private Visualizacao.PanelRound panelRound13;
    private Visualizacao.PanelRound panelRound14;
    private Visualizacao.PanelRound panelRound2;
    private Visualizacao.PanelRound panelRound3;
    private Visualizacao.PanelRound panelRound4;
    private Visualizacao.PanelRoundBorda panelRoundBorda1;
    private Visualizacao.PanelRoundBorda panelRoundBorda2;
    private Visualizacao.PanelRoundBorda panelRoundBorda4;
    private Visualizacao.PanelRoundBorda panelRoundBorda5;
    private Visualizacao.PanelRoundBorda panelRoundBorda6;
    private Visualizacao.PanelRoundBorda panelRoundBorda7;
    private Visualizacao.CustomScrollPane panelScrollMundos;
    private Visualizacao.PanelSlide panelSlide;
    private Visualizacao.PanelSombra panelSombra3;
    private Visualizacao.PanelSombra panelSombra5;
    private Visualizacao.PanelSombra panelSombra6;
    private Visualizacao.PanelSombra panelSombra7;
    private Visualizacao.PanelRound panel_fogo;
    private Visualizacao.PanelRound panel_fogo_grande;
    private Visualizacao.PanelRound panel_gelo;
    private Visualizacao.PanelRound panel_gelo_grande;
    private Visualizacao.PanelRound panel_natural;
    private Visualizacao.PanelRound panel_natural_grande;
    // End of variables declaration//GEN-END:variables
}
