package Visualizacao;

import Controle.Conexao;
import Modelagem.Aluno;
import Modelagem.Session;
import Modelagem.VerificadorFases;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class FRegiao extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private Aluno alunoLogado;
    private int idAluno;

    public FRegiao() {
        initComponents();
        conexao = Conexao.conecta();
        alunoLogado = Session.getInstance().getAlunoLogado();

        idAluno = alunoLogado.getIdAluno();
        double pontos = alunoLogado.getPontosTotais();
        String ranque = alunoLogado.getRanque();

        lbl_pontos.setText(Double.toString(pontos));
        lbl_ranque.setText(ranque);

        String verConquistas = "select count(*) from alunosXconquistas where idAluno = ?";
        try {
            pst = conexao.prepareStatement(verConquistas);
            pst.setInt(1, idAluno);
            rs = pst.executeQuery();

            if (rs.next()) {
                int qtdMedalhas = rs.getInt(1);
                lbl_medalhas.setText(Integer.toString(qtdMedalhas));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        Color pretoComOpacidade = new Color(0, 0, 0, 55);
        Color Opacidade = new Color(0, 0, 0, 0);
        panelRoundBorda2.setBackground(Opacidade);

        this.setLayout(new BorderLayout());
        this.add(customScrollPane1, BorderLayout.CENTER);
        this.add(menu, BorderLayout.SOUTH);

        panel_linha1.setLineColor(Color.WHITE);
        panel_linha2.setLineColor(Color.WHITE);
        panel_linha3.setLineColor(Color.WHITE);
        panel_linha4.setLineColor(Color.WHITE);

        VerificadorFases vfases = new VerificadorFases(conexao);
        String[] estadosFases = vfases.verificarFases(1, idAluno); // Verifica as fases da região 1
        
        if (estadosFases[0].equals("ok")) {
            panel_linha1.setLineColor(new Color(72, 72, 72));
        }
        if (estadosFases[1].equals("ok")) {
            panel_linha2.setLineColor(new Color(72, 72, 72));
        }
        if (estadosFases[2].equals("ok")) {
            panel_linha3.setLineColor(new Color(72, 72, 72));
        }
        if (estadosFases[3].equals("ok")) {
            panel_linha4.setLineColor(new Color(72, 72, 72));
        }
        
        verPrimeiraMedalha();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuHamburguer = new javax.swing.JLabel();
        customScrollPane1 = new Visualizacao.CustomScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Visualizacao.PanelRound();
        fase4 = new Visualizacao.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        fase5 = new Visualizacao.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        fase3 = new Visualizacao.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        fase2 = new Visualizacao.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        panelSelecionar = new Visualizacao.PanelRoundBorda();
        itemLabel = new javax.swing.JLabel();
        inicio = new Visualizacao.PanelRoundBorda();
        jLabel8 = new javax.swing.JLabel();
        panelRoundBorda2 = new Visualizacao.PanelRoundBorda();
        panelRound2 = new Visualizacao.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_linha1 = new Visualizacao.DiagonalDashedLinePanel();
        panel_linha4 = new Visualizacao.DiagonalDashedLinePanel();
        panel_linha2 = new Visualizacao.DiagonalDashedLinePanel();
        panel_linha3 = new Visualizacao.DiagonalDashedLinePanel();
        panelSombra1 = new Visualizacao.PanelSombra();
        lbl_pontos = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelSombra2 = new Visualizacao.PanelSombra();
        lbl_medalhas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelSombra4 = new Visualizacao.PanelSombra();
        lbl_ranque = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        menu.setBackground(new java.awt.Color(72, 72, 72));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone perfil.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone home.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        menuHamburguer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone menu hamburguer.png"))); // NOI18N
        menuHamburguer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHamburguerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuHamburguerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuHamburguerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(menuHamburguer)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuHamburguer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(128, 210, 91));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        fase4.setBackground(new java.awt.Color(72, 72, 72));
        fase4.setPreferredSize(new java.awt.Dimension(90, 90));
        fase4.setRoundBottomLeft(100);
        fase4.setRoundBottomRight(100);
        fase4.setRoundTopLeft(100);
        fase4.setRoundTopRight(100);
        fase4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fase4MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("03");

        javax.swing.GroupLayout fase4Layout = new javax.swing.GroupLayout(fase4);
        fase4.setLayout(fase4Layout);
        fase4Layout.setHorizontalGroup(
            fase4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fase4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        fase4Layout.setVerticalGroup(
            fase4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fase4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        fase5.setBackground(new java.awt.Color(72, 72, 72));
        fase5.setPreferredSize(new java.awt.Dimension(90, 90));
        fase5.setRoundBottomLeft(100);
        fase5.setRoundBottomRight(100);
        fase5.setRoundTopLeft(100);
        fase5.setRoundTopRight(100);
        fase5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fase5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("04");

        javax.swing.GroupLayout fase5Layout = new javax.swing.GroupLayout(fase5);
        fase5.setLayout(fase5Layout);
        fase5Layout.setHorizontalGroup(
            fase5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fase5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        fase5Layout.setVerticalGroup(
            fase5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fase5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        fase3.setBackground(new java.awt.Color(72, 72, 72));
        fase3.setPreferredSize(new java.awt.Dimension(90, 90));
        fase3.setRoundBottomLeft(100);
        fase3.setRoundBottomRight(100);
        fase3.setRoundTopLeft(100);
        fase3.setRoundTopRight(100);
        fase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fase3MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("02");

        javax.swing.GroupLayout fase3Layout = new javax.swing.GroupLayout(fase3);
        fase3.setLayout(fase3Layout);
        fase3Layout.setHorizontalGroup(
            fase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fase3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(29, 29, 29))
        );
        fase3Layout.setVerticalGroup(
            fase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fase3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        fase2.setBackground(new java.awt.Color(72, 72, 72));
        fase2.setPreferredSize(new java.awt.Dimension(90, 90));
        fase2.setRoundBottomLeft(100);
        fase2.setRoundBottomRight(100);
        fase2.setRoundTopLeft(100);
        fase2.setRoundTopRight(100);
        fase2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fase2MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("01");

        javax.swing.GroupLayout fase2Layout = new javax.swing.GroupLayout(fase2);
        fase2.setLayout(fase2Layout);
        fase2Layout.setHorizontalGroup(
            fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fase2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        fase2Layout.setVerticalGroup(
            fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fase2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelSelecionar.setBackground(new java.awt.Color(72, 72, 72));
        panelSelecionar.setBorderWidth(5);
        panelSelecionar.setPreferredSize(new java.awt.Dimension(90, 90));
        panelSelecionar.setRadius(100);
        panelSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSelecionarMouseClicked(evt);
            }
        });

        itemLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelSelecionarLayout = new javax.swing.GroupLayout(panelSelecionar);
        panelSelecionar.setLayout(panelSelecionarLayout);
        panelSelecionarLayout.setHorizontalGroup(
            panelSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelecionarLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelSelecionarLayout.setVerticalGroup(
            panelSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelecionarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        inicio.setBackground(new java.awt.Color(72, 72, 72));
        inicio.setBorderWidth(5);
        inicio.setPreferredSize(new java.awt.Dimension(90, 90));
        inicio.setRadius(100);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-bandeira.png"))); // NOI18N

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(21, 21, 21))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelRoundBorda2.setBackground(new java.awt.Color(72, 72, 72));
        panelRoundBorda2.setBorderWidth(6);
        panelRoundBorda2.setImg(null);
        panelRoundBorda2.setRadius(30);
        panelRoundBorda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRoundBorda2MouseClicked(evt);
            }
        });

        panelRound2.setBackground(new java.awt.Color(72, 72, 72));
        panelRound2.setImg(new ImageIcon("src/Imagens/img-natureza-fundo.png"));
        panelRound2.setRoundBottomLeft(23);
        panelRound2.setRoundBottomRight(23);
        panelRound2.setRoundTopLeft(23);
        panelRound2.setRoundTopRight(23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Região 01 - Floresta");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mundo 01");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRoundBorda2Layout = new javax.swing.GroupLayout(panelRoundBorda2);
        panelRoundBorda2.setLayout(panelRoundBorda2Layout);
        panelRoundBorda2Layout.setHorizontalGroup(
            panelRoundBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundBorda2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        panelRoundBorda2Layout.setVerticalGroup(
            panelRoundBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundBorda2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        panel_linha1.setBackground(new java.awt.Color(255, 255, 255));
        panel_linha1.setDirection(1);
        panel_linha1.setLineColor(new java.awt.Color(72, 72, 72));
        panel_linha1.setPreferredSize(new java.awt.Dimension(40, 40));
        panel_linha1.setStrokeWidth(6.0F);

        javax.swing.GroupLayout panel_linha1Layout = new javax.swing.GroupLayout(panel_linha1);
        panel_linha1.setLayout(panel_linha1Layout);
        panel_linha1Layout.setHorizontalGroup(
            panel_linha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel_linha1Layout.setVerticalGroup(
            panel_linha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panel_linha4.setBackground(new java.awt.Color(255, 255, 255));
        panel_linha4.setLineColor(new java.awt.Color(72, 72, 72));
        panel_linha4.setPreferredSize(new java.awt.Dimension(40, 40));
        panel_linha4.setStrokeWidth(6.0F);

        javax.swing.GroupLayout panel_linha4Layout = new javax.swing.GroupLayout(panel_linha4);
        panel_linha4.setLayout(panel_linha4Layout);
        panel_linha4Layout.setHorizontalGroup(
            panel_linha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel_linha4Layout.setVerticalGroup(
            panel_linha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panel_linha2.setBackground(new java.awt.Color(255, 255, 255));
        panel_linha2.setDirection(1);
        panel_linha2.setLineColor(new java.awt.Color(72, 72, 72));
        panel_linha2.setPreferredSize(new java.awt.Dimension(40, 40));
        panel_linha2.setStrokeWidth(6.0F);

        javax.swing.GroupLayout panel_linha2Layout = new javax.swing.GroupLayout(panel_linha2);
        panel_linha2.setLayout(panel_linha2Layout);
        panel_linha2Layout.setHorizontalGroup(
            panel_linha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel_linha2Layout.setVerticalGroup(
            panel_linha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panel_linha3.setBackground(new java.awt.Color(255, 255, 255));
        panel_linha3.setLineColor(new java.awt.Color(72, 72, 72));
        panel_linha3.setPreferredSize(new java.awt.Dimension(40, 40));
        panel_linha3.setStrokeWidth(6.0F);

        javax.swing.GroupLayout panel_linha3Layout = new javax.swing.GroupLayout(panel_linha3);
        panel_linha3.setLayout(panel_linha3Layout);
        panel_linha3Layout.setHorizontalGroup(
            panel_linha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panel_linha3Layout.setVerticalGroup(
            panel_linha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(panelSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(panelRoundBorda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_linha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panel_linha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fase3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                            .addComponent(panel_linha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(69, 69, 69))))))
                        .addGroup(panelRound1Layout.createSequentialGroup()
                            .addComponent(fase5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panel_linha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fase4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)))
                .addGap(56, 56, 56))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(panelSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(panelRoundBorda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(panel_linha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(fase5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fase4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_linha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_linha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(panel_linha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addComponent(inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        panelSombra1.setBackground(new java.awt.Color(255, 255, 255));
        panelSombra1.setPreferredSize(new java.awt.Dimension(131, 54));
        panelSombra1.setShadowOpacity(0.3F);

        lbl_pontos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_pontos.setForeground(new java.awt.Color(72, 72, 72));
        lbl_pontos.setText("100");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-fogo.png"))); // NOI18N

        javax.swing.GroupLayout panelSombra1Layout = new javax.swing.GroupLayout(panelSombra1);
        panelSombra1.setLayout(panelSombra1Layout);
        panelSombra1Layout.setHorizontalGroup(
            panelSombra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSombra1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_pontos)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelSombra1Layout.setVerticalGroup(
            panelSombra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSombra1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(panelSombra1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_pontos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSombra2.setBackground(new java.awt.Color(255, 255, 255));
        panelSombra2.setPreferredSize(new java.awt.Dimension(131, 47));
        panelSombra2.setShadowOpacity(0.3F);

        lbl_medalhas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_medalhas.setForeground(new java.awt.Color(72, 72, 72));
        lbl_medalhas.setText("10");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-moeda.png"))); // NOI18N

        javax.swing.GroupLayout panelSombra2Layout = new javax.swing.GroupLayout(panelSombra2);
        panelSombra2.setLayout(panelSombra2Layout);
        panelSombra2Layout.setHorizontalGroup(
            panelSombra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSombra2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(lbl_medalhas)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelSombra2Layout.setVerticalGroup(
            panelSombra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSombra2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_medalhas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSombra2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelSombra4.setBackground(new java.awt.Color(255, 255, 255));
        panelSombra4.setPreferredSize(new java.awt.Dimension(131, 47));
        panelSombra4.setShadowOpacity(0.3F);

        lbl_ranque.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ranque.setForeground(new java.awt.Color(72, 72, 72));
        lbl_ranque.setText("1");
        lbl_ranque.setToolTipText("");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-estrela.png"))); // NOI18N

        javax.swing.GroupLayout panelSombra4Layout = new javax.swing.GroupLayout(panelSombra4);
        panelSombra4.setLayout(panelSombra4Layout);
        panelSombra4Layout.setHorizontalGroup(
            panelSombra4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSombra4Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lbl_ranque)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelSombra4Layout.setVerticalGroup(
            panelSombra4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSombra4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_ranque)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelSombra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(panelSombra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(panelSombra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSombra2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(panelSombra4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(panelSombra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        customScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6jLabel1MouseClicked
        new FPerfil(this).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6jLabel1MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel7MouseExited

    private void menuHamburguerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHamburguerMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuHamburguerMouseEntered

    private void menuHamburguerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHamburguerMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_menuHamburguerMouseExited

    private void fase5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fase5MouseClicked
        new FFaseObservacao().setVisible(true);
        dispose();
    }//GEN-LAST:event_fase5MouseClicked

    private void fase4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fase4MouseClicked
        new FFaseOuvir().setVisible(true);
        dispose();
    }//GEN-LAST:event_fase4MouseClicked

    private void fase3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fase3MouseClicked
        new FFaseNumeros1().setVisible(true);
        dispose();
    }//GEN-LAST:event_fase3MouseClicked

    private void fase2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fase2MouseClicked
        new FFaseLigar().setVisible(true);
        dispose();
    }//GEN-LAST:event_fase2MouseClicked

    private void menuHamburguerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHamburguerMouseClicked
        new FOpcoes(this).setVisible(true);
        dispose();
    }//GEN-LAST:event_menuHamburguerMouseClicked

    private void panelRoundBorda2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRoundBorda2MouseClicked
        new FMundos().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelRoundBorda2MouseClicked

    private void panelSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSelecionarMouseClicked
        openItemSelectionDialog();
    }//GEN-LAST:event_panelSelecionarMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new FMundos().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void verPrimeiraMedalha() {
        String verConquistas = "select c.iconMedalha from alunosXconquistas axc "
                + "join conquistas c using(idConquista) "
                + "join alunos a using(idAluno) "
                + "where a.idAluno = ? and nomeConquista = ?;";
        try {
            pst = conexao.prepareStatement(verConquistas);
            pst.setInt(1, idAluno);
            pst.setString(2, alunoLogado.getMedalhaAtiva());
            rs = pst.executeQuery();

            if (rs.next()) {
                String caminhoMedalha = rs.getString(1);
                Icon iconMedalha = new ImageIcon("src/Imagens/" + caminhoMedalha);

                itemLabel.setIcon(iconMedalha);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void openItemSelectionDialog() {
        // Cria o diálogo de seleção de itens
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(itemLabel), "Selecionar Item", true);
        dialog.setUndecorated(true); // Remove decorações da janela 
        dialog.setBackground(new Color(0, 0, 0, 0)); // Fundo transparente
        dialog.getContentPane().setBackground(new Color(0, 0, 0, 0)); // Fundo transparente do contentPane

        // Painel para adicionar itens ao diálogo
        PanelRoundBorda itemSelectionPanel = new PanelRoundBorda();
        itemSelectionPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 15, 15));
        itemSelectionPanel.setRadius(40);
        itemSelectionPanel.setBorderWidth(3);
        itemSelectionPanel.setBackground(Color.WHITE);
        itemSelectionPanel.setPreferredSize(new Dimension(170, 80));

        String verConquistas = "select c.nomeConquista, c.iconMedalha from alunosXconquistas axc "
                + "join conquistas c using(idConquista) "
                + "join alunos a using(idAluno) "
                + "where a.idAluno = ?;";
        boolean temItems = false;
        try {
            pst = conexao.prepareStatement(verConquistas);
            pst.setInt(1, idAluno);
            rs = pst.executeQuery();

            while (rs.next()) {
                String nomeConquista = rs.getString(1);
                String caminhoMedalha = rs.getString(2);
                Icon iconMedalha = new ImageIcon("src/Imagens/" + caminhoMedalha);

                JLabel item = new JLabel();
                item.setIcon(iconMedalha);

                item.addMouseListener(new MouseAdapter() {
                    public void mouseClicked(MouseEvent e) {
                        // Quando um item é selecionado, atualiza o item no painel principal
                        alunoLogado.setMedalhaAtiva(nomeConquista);
                        alunoLogado.salvarMedalha();
                        itemLabel.setIcon(iconMedalha);
                        dialog.dispose(); // Fecha o diálogo
                    }
                });

                itemSelectionPanel.add(item);
                temItems = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        if (temItems) {
            // Adiciona o painel de seleção de itens ao diálogo
            dialog.add(itemSelectionPanel);

            // Define o tamanho e torne o diálogo visível
            dialog.pack();
            dialog.setLocationRelativeTo(itemLabel);
            dialog.setVisible(true);
        } else {
            // Exibe uma mensagem caso não existam conquistas
            ImageIcon icon = new ImageIcon("src/Imagens/icon-conquista-alerta.png");
            AlertaGeral alert = new AlertaGeral(FRegiao.this, icon, "Nenhuma Medalha", "Você ainda não possui medalhas.", 25, 25);
            alert.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRegiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRegiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRegiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRegiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRegiao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Visualizacao.CustomScrollPane customScrollPane1;
    private Visualizacao.PanelRound fase2;
    private Visualizacao.PanelRound fase3;
    private Visualizacao.PanelRound fase4;
    private Visualizacao.PanelRound fase5;
    private Visualizacao.PanelRoundBorda inicio;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_medalhas;
    private javax.swing.JLabel lbl_pontos;
    private javax.swing.JLabel lbl_ranque;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuHamburguer;
    private Visualizacao.PanelRound panelRound1;
    private Visualizacao.PanelRound panelRound2;
    private Visualizacao.PanelRoundBorda panelRoundBorda2;
    private Visualizacao.PanelRoundBorda panelSelecionar;
    private Visualizacao.PanelSombra panelSombra1;
    private Visualizacao.PanelSombra panelSombra2;
    private Visualizacao.PanelSombra panelSombra4;
    private Visualizacao.DiagonalDashedLinePanel panel_linha1;
    private Visualizacao.DiagonalDashedLinePanel panel_linha2;
    private Visualizacao.DiagonalDashedLinePanel panel_linha3;
    private Visualizacao.DiagonalDashedLinePanel panel_linha4;
    // End of variables declaration//GEN-END:variables
}
